# Generated by Django 3.0.7 on 2023-05-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_add_username_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
